### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by oghmios** [cgkineo/adapt-cover-menu#1]
i can't use that plugin. When I copy the code and use with my menus adapt crashes. Could you tell me where I need to put that plugin? It's a menu plugin? Do I need to uninstall latest menu plugin or can I work with two?

**Comment by oliverfoster** [comment]
i'm afraid you can only have one menu per course unless you have the menu controller installed.

if you're using v2 of the framework take from branch v2 > https://github.com/cgkineo/adapt-cover-menu/tree/v2

if you want more than one menu, install https://github.com/cgkineo/adapt-menu-controller and follow the readme directions

**Comment by oghmios** [comment]
Ok, thanks for all!

**Comment by oliverfoster** [comment]
can you close this issue when you're happy with the result? :)
