### ISSUE TITLE
Why is it only possible to have a limit of 10 slides

### ISSUE THREAD

**Issue by zarek3333** [cgkineo/adapt-cover-menu#13]
Why is it only possible to have a limit of 10 slides. Is this because of the data-item-index can only taking single digits as it is right now? Just wonder cause I have 12 pages and would love to use this menu.

**Comment by moloko** [comment]
it's just a 'sensible default' to keep the number of CSS selectors to a sane amount for typical usage. If you need to change it, just amend the LESS variable `item-max-count` in coverMenu.less
