### ISSUE TITLE
Must supply a pluginName to change a locked attribute

### ISSUE THREAD

**Issue by zarek3333** [cgkineo/adapt-cover-menu#14]
Getting an error in Framework 4 coming from the underscore.min.js that states: Must supply a pluginName to change a locked attribute.

This is happening when a locked page is added. Thanks for your help on max count in less file I overlooked that and I get your point if only the customers would. LOL

**Comment by moloko** [comment]
I don't think that error is anything to do with coverMenu. Unless it's causing a problem you can safely ignore it.
