### ISSUE TITLE
no implementation of setupIndicatorLayout?

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-cover-menu#4]
adapt-cover.js (master line 54; v2 line 68) refers to this.setupIndicatorLayout but I cannot locate it in adapt-cover-menu or anywhere in the framework. Am I overlooking it?

**Comment by chris-steele** [comment]
@chucklorenz realise this is long, long ago, but to answer your question - it has a purpose that only its original author knows - I think it's long been orphaned so will remove the line.
