### ISSUE TITLE
Is it possible to use this Plugin with the Adapt Authoring-Tool?

### ISSUE THREAD

**Issue by RickVanLouis** [cgkineo/adapt-cover-menu#8]
Hey guys,

cause of Proxy-Issues in my company I'm not able to use the Framework of Adapt. So I worked on a workaround and now I'm using the Authoring Tool to create courses. I was wondering if there any solution exists with which I can implement this nice plugin. Using the Plugin-Manager of the Authoring Tool doesn't work. "Error: Package does not contain a schema" is the error I get while I'm trying to upload this plugin as ZIP. Maybe it is possible to release the properties.schema-file which is needed.

Thank you very much.

**Comment by moloko** [comment]
Hi @RickVanLouis sure if one of us gets time we can look at this for you. 

Alternatively, they're not actually that hard to put together (just a bit tedious and fiddly at times). If you wanted to give it a go yourself there's some documentation [here](https://github.com/adaptlearning/adapt_authoring/wiki/Properties-Schema) and of course you can look at/base it on examples from other menus/plugins

**Comment by RickVanLouis** [comment]
Thank you moloko. I will try to create my own properties.schema-file, but I have to do a lot other stuff before (for my company), so I will use the default menu for my first courses and will implement further features in the future, Hopefully there is some time for me to implement them. 

Thanks

**Comment by chris-steele** [comment]
@RickVanLouis, @moloko this has been added to the AT branch and currently awaits approval for merging into master.

**Comment by hbaileylxd** [comment]
We can haz properties.schema now plz? K thnx bai!

**Comment by moloko** [comment]
@tomgreenfield does the 'refactor' branch work OK with the AT?

**Comment by tomgreenfield** [comment]
Sure does.
